# Generated by Django 4.2.6 on 2023-10-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_sold', models.PositiveIntegerField()),
                ('customer_count', models.PositiveIntegerField()),
                ('employee_performance', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
    ]
