# Generated by Django 4.2.6 on 2023-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_salesanalytics_total_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesanalytics',
            name='customer_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesanalytics',
            name='product_sold',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
