# Generated by Django 4.2.6 on 2023-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_salesanalytics_customer_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesanalytics',
            name='employee_performance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
